Counting DNA Nucleotides
# A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.
# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.


def numbernecleotides(sequence):
    nucleotidesdict = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for nucleo in sequence:
        nucleotidesdict[nucleo] += 1
    return nucleotidesdict

dna_string = "AGCCGCTTTACGCATTCAGGAGAGTGCGAAAGTGGTATCGATCGGCATCTTAGTTTGTCATGTAGACGGCCCCTTTAAGGTGCACGCAGCTCCACTTTGCCTTGCTTATCGGGTTTGGCCAACCGCACATATAGAACAGAAGATAGTCAACCGGCAGCTCCCCTCAATCGCAAGTACTGTAAATTCAGGAGCTCGTTTGTCCGTAACTTGGTAGGGCGTAGTTTCCTGCGAGCCTGACGCTGTCCGAAAGAGCGTCTAAAGTTAACGACGCTAGCAACTTAAAAGTGCTATCGTAACTTCGGTTTCCACCTGAAAATAGTTCTGATCGTCGTGAGAAAGCATTGTAGGGGGACATCCTGCGTAACTAGGCGAGTGGTCCTCTGGCTAATGATCCGATCCCCTTGACAAAACCCTACGACAAGTGTTTAACCCGATGATGTATCGACCTTGAGCGCGAGAAGCACAAAGCCCTCGTAGTGCGACTGCTCTGTAAAAGGTTTCCAAGCTCTAGAAACCGAGCGAACTTGTGATCATCCCTGGCGCAGGCTTTTAAAATGGATTTAAATTGCTCAGAATAGGAGCAGAACGAACTTGGTTCTTAGGAGACCATAAGAGCACTAACGCGCAGCTGTCGTAGCTTACCTCAAATTCAAAATAGCCTTAGCGGACGGAATGTCAAAAGGTCGCACGCAACAGGGGACCTAGTAAAGACTACGTAACTGGACGTCCACCGCACAAAGTCTGTCCTGTTTCGACATTGGCGCCGACCCGGGTCAATCTCTGGCCGTTCCAAATGATCTCACAAGTGGGGCCTAACACACCATGGGGGATGTACGAAGCAAAAG"
result = numbernecleotides(dna_string)
print(result)

for key,value in dict.items(result):
    print(value)
       
       ===============================

229
209
210
197