#Finding a Motif in DNA

sequence = "GATATATGCATATACTT"
substring = "ATAT"
locations_list = []
# 
for i in range(0, len(sequence)):
    if sequence[i: i + len(substring)] == substring:
        locations_list.append(i + 1)
print(locations_list)
[2, 4, 10]
# To get rid of the "[,]", I had use these commands which I searched for them in python. 
print(*locations_list, sep = "")
# or                                               ===================> 2 4 10
print(' '.join(map(str, locations_list)))

# my_dataset:
sequence = "TCTTTGATCTTTGATCGCATCTTTGATCTTTGAATAACCCCGCTTCTTTGAACACTCTTTGATCGTCTTTGATTCTTTGATCTTTGAATCTTTGAGTCTTTGACCTCTTTGAATACACTTCTTTGAGATATCTTTGAGCTTAAGGGTTTCTAGTCTCTTTGATCTTTGAGGTCGGTCTTTGATTCTTTGAGATTCTTTGAAAATCTTTGATAATCTTTGAGTGATCTTTGATTGTCTTTGATTCTTTGAACATCTTTGACCCAAGATCAGTAACACATGACTCTTTGATACTCTTTGATCTTTGATCTTTGATTCTTTGAATCTTTGACCTCTTTGATAACAAGTTCTTTGATCTTTGATCTTTGATCTTTGAGCCTTTCTTTGATCTTTGAATCTTTGATCTTTGATTATTCTTTGATGGCCTCTTTGAAAATTCTTTGACATTTTCTTTGATCTTTGACGTGAGATTTCTTTGAGTCTCTTTGAGAGACTAGAGCCTCTTTGATCTTTGACATCTTTGATTTTCTTTGAACGTCTTTGATCTTTGATCTTTGACCTACTGTCTTTGAGATCTTTGATCTTTGATCTTTGAATCTTTGATCTTTGAGGCCCCCTCTTTGATCTTTGATCTTTGACATCTTTGATGTCTTTGATCTTTGACTCTTTGATCTTTGAGTCTTTGAAGTGGCTCTTTGAATCTTTGAAATAGTAACCCCGTCTTTGACAAGTCTTTGATCTTTGACATCTTTGAGAGTTATCTTTGAATTTCTCTTTGACTTCTCTTTGATCTTTGAATTTAATCTTTGATCTTTGAACTCCTCTTTGA"
substring = "TCTTTGATC"
locations_list = []     1 8 20 56 74 156 292 299 346 353 360 379 394 447 499 535 542 572 579 594 615 622 647 662 729 781 801